server:
  port: 8080
  servlet:
    jsp:
      init-parameters:
        development: true
    session:
      cookie:
        name: WOORIAT
spring:
  profiles:
    active: local

---
# local
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  profiles: local
  serviceUrl: devsite.gsitm.com
  mvc:
    view:
      prefix: /WEB-INF/jsp/views/
      suffix: .jsp
  datasource:
     url: jdbc:sqlserver://211.232.50.135:1433;databaseName=WOORIAT
     username: "wooriat"
     password: "woori_at_1234$#@!"
     driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        show_sql: true # systemOut log
        format_sql: true

logging:
  level:
#    root: warn
    org.hibernate.SQL: debug
    org.hibernate.type: trace
#    com.gsitm.admin: debug
#  path: C:\dev\logs\gsitm\
#  config: classpath:lgbs.xml_bak

---
# dev
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  profiles: dev
  serviceUrl: devsite.gsitm.com
  mvc:
    view:
      prefix: /WEB-INF/jsp/views/
      suffix: .jsp
  datasource:
    jndi-name: jdbc/homedb
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      #      naming:
      #        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
#        show_sql: true # systemOut log
#        format_sql: true

logging:
  level:
    root: warn
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    com.gsitm.admin: debug
  path: /home/gsitm/gsitmAdmin/log/
#  config: classpath:logback-spring.xml


---
# prod
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  profiles: prod
  serviceUrl: stgsite.gsitm.com
  mvc:
    view:
      prefix: /WEB-INF/jsp/views/
      suffix: .jsp
  datasource:
    jndi-name: jdbc/homedb
  jpa:
    hibernate:
      ddl-auto: update
      #      naming:
      #        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
#        show_sql: true # systemOut log
#        format_sql: true

logging:
  level:
    root: warn
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    com.gsitm.admin: debug